EmployeeManagement/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EmployeeManagementSystem.Models;

namespace EmployeeManagementSystem.Controllers
{
    public class EmployeesController : Controller
    {
        private EMSDbContext db = new EMSDbContext();

        // GET: Employees
        public ActionResult Index()
        {
            var employees = db.Employees.Include(e => e.Shift);
            return View(employees.ToList());
        }

        // GET: Employees/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // GET: Employees/Create
        public ActionResult Create()
        {
            ViewBag.ShiftId = new SelectList(db.Shifts, "ShiftId", "ShiftName");
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EmployeeId,FullName,Designation,DateOfJoining,Salary,ContactNumber,Email,Address,ShiftId")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                db.Employees.Add(employee);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ShiftId = new SelectList(db.Shifts, "ShiftId", "ShiftName", employee.ShiftId);
            return View(employee);
        }

        // GET: Employees/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            ViewBag.ShiftId = new SelectList(db.Shifts, "ShiftId", "ShiftName", employee.ShiftId);
            return View(employee);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EmployeeId,FullName,Designation,DateOfJoining,Salary,ContactNumber,Email,Address,ShiftId")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                db.Entry(employee).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ShiftId = new SelectList(db.Shifts, "ShiftId", "ShiftName", employee.ShiftId);
            return View(employee);
        }

        // GET: Employees/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Employee employee = db.Employees.Find(id);
            db.Employees.Remove(employee);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EmployeeManagement/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EmployeeManagementSystem.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

EmployeeManagement/Controllers/LeavesController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using EmployeeManagementSystem.Models;

namespace EmployeeManagementSystem.Controllers
{
    public class LeaveController : Controller
    {
        private EMSDbContext db = new EMSDbContext();

        public ActionResult Index() =>
            View(db.Leaves.Include(l => l.Employee).ToList());

        public ActionResult Details(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            Leave leave = db.Leaves.Find(id);
            if (leave == null) return HttpNotFound();
            return View(leave);
        }

        public ActionResult Create()
        {
            ViewBag.EmployeeId = new SelectList(db.Employees, "EmployeeId", "FullName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Leave leave)
        {
            if (ModelState.IsValid)
            {
                db.Leaves.Add(leave);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EmployeeId = new SelectList(db.Employees, "EmployeeId", "FullName", leave.EmployeeId);
            return View(leave);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            Leave leave = db.Leaves.Find(id);
            if (leave == null) return HttpNotFound();
            ViewBag.EmployeeId = new SelectList(db.Employees, "EmployeeId", "FullName", leave.EmployeeId);
            return View(leave);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Leave leave)
        {
            if (ModelState.IsValid)
            {
                db.Entry(leave).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EmployeeId = new SelectList(db.Employees, "EmployeeId", "FullName", leave.EmployeeId);
            return View(leave);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            Leave leave = db.Leaves.Find(id);
            if (leave == null) return HttpNotFound();
            return View(leave);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Leave leave = db.Leaves.Find(id);
            db.Leaves.Remove(leave);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing) db.Dispose();
            base.Dispose(disposing);
        }
    }
}

EmployeeManagement/Controllers/PayrollsController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using EmployeeManagementSystem.Models;

namespace EmployeeManagementSystem.Controllers
{
    public class PayrollController : Controller
    {
        private EMSDbContext db = new EMSDbContext();

        public ActionResult Index() =>
            View(db.Payrolls.Include(p => p.Employee).ToList());

        public ActionResult Details(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            Payroll payroll = db.Payrolls.Find(id);
            if (payroll == null) return HttpNotFound();
            return View(payroll);
        }

        public ActionResult Create()
        {
            ViewBag.EmployeeId = new SelectList(db.Employees, "EmployeeId", "FullName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Payroll payroll)
        {
            if (ModelState.IsValid)
            {
                db.Payrolls.Add(payroll);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EmployeeId = new SelectList(db.Employees, "EmployeeId", "FullName", payroll.EmployeeId);
            return View(payroll);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Payroll payroll = db.Payrolls.Find(id);
            if (payroll == null) return HttpNotFound();
            ViewBag.EmployeeId = new SelectList(db.Employees, "EmployeeId", "FullName", payroll.EmployeeId);
            return View(payroll);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Payroll payroll)
        {
            if (ModelState.IsValid)
            {
                db.Entry(payroll).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EmployeeId = new SelectList(db.Employees, "EmployeeId", "FullName", payroll.EmployeeId);
            return View(payroll);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            Payroll payroll = db.Payrolls.Find(id);
            if (payroll == null) return HttpNotFound();
            return View(payroll);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Payroll payroll = db.Payrolls.Find(id);
            db.Payrolls.Remove(payroll);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing) db.Dispose();
            base.Dispose(disposing);
        }
    }
}

EmployeeManagement/Controllers/ShiftsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using EmployeeManagementSystem.Models;

namespace EmployeeManagementSystem.Controllers
{
    public class ShiftController : Controller
    {
        private EMSDbContext db = new EMSDbContext();

        // GET: /Shift/
        public ActionResult Index()
        {
            var shifts = db.Shifts.ToList();
            return View(shifts);
        }

        // GET: /Shift/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var shift = db.Shifts.Find(id);
            if (shift == null)
                return HttpNotFound();

            return View(shift);
        }

        // GET: /Shift/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Shift/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Shift shift)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.Shifts.Add(shift);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (DbEntityValidationException dbEx)
                {
                    // Unwrap EF validation errors into ModelState
                    foreach (var validationErrors in dbEx.EntityValidationErrors)
                    {
                        foreach (var error in validationErrors.ValidationErrors)
                        {
                            ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                        }
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Unable to save shift. " + ex.Message);
                }
            }

            // If we got this far, something failed; redisplay form
            return View(shift);
        }

        // GET: /Shift/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var shift = db.Shifts.Find(id);
            if (shift == null)
                return HttpNotFound();

            return View(shift);
        }

        // POST: /Shift/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Shift shift)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.Entry(shift).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (DbEntityValidationException dbEx)
                {
                    foreach (var validationErrors in dbEx.EntityValidationErrors)
                    {
                        foreach (var error in validationErrors.ValidationErrors)
                        {
                            ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                        }
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Unable to update shift. " + ex.Message);
                }
            }

            // Redisplay form on error
            return View(shift);
        }

        // GET: /Shift/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var shift = db.Shifts.Find(id);
            if (shift == null)
                return HttpNotFound();

            return View(shift);
        }

        // POST: /Shift/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                var shift = db.Shifts.Find(id);
                db.Shifts.Remove(shift);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Unable to delete shift. " + ex.Message);
                // If deletion fails, redisplay the confirmation view
                var shift = db.Shifts.Find(id);
                return View("Delete", shift);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                db.Dispose();
            base.Dispose(disposing);
        }
    }
}

EmployeeManagement/Views/Home/About.cshtml
@{
    ViewBag.Title = "About Arafat Paints & Varnish Ltd";
    ViewBag.Message = "Welcome to the world of premium paints and coatings!";
}

<main aria-labelledby="title" class="container">
    <h2 id="title" class="text-center my-4">@ViewBag.Title</h2>
    <h3 class="text-center mb-4">@ViewBag.Message</h3>

    <div class="jumbotron bg-primary text-white text-center">
        <h4>Welcome to Arafat Paints & Varnish Ltd</h4>
        <p>Your trusted partner in providing top-quality paints and coatings for homes, businesses, and industrial applications.</p>
    </div>

    <p>Welcome to <strong>Arafat Paints & Varnish Ltd</strong>, your trusted partner in providing top-quality paints and coatings for homes, businesses, and industrial applications. With over a decade of experience, we pride ourselves on delivering durable, vibrant, and eco-friendly paint solutions to meet all of your decorative and functional needs.</p>

    <p>We are committed to helping you enhance the beauty and longevity of your spaces with our wide range of innovative products. Whether you're looking for exterior or interior paints, coatings, or specialized finishes, we have something to suit every project.</p>

    <h4 class="mt-5">Our Mission</h4>
    <p>Our mission is to provide customers with the best paints and coatings, backed by superior customer service, sustainability, and technical expertise. We strive to contribute to a greener world by using eco-friendly ingredients and reducing our environmental footprint through responsible practices.</p>

    <h4 class="mt-5">Our Values</h4>
    <ul>
        <li><strong>Quality:</strong> We believe in offering only the highest quality products for your projects.</li>
        <li><strong>Innovation:</strong> We continuously evolve our product offerings, incorporating the latest trends and technologies.</li>
        <li><strong>Customer Commitment:</strong> Our customers’ satisfaction is our top priority. We listen to your needs and deliver on promises.</li>
        <li><strong>Environmental Responsibility:</strong> We are dedicated to preserving the environment and creating products that are safe for people and nature.</li>
    </ul>

    <h4 class="mt-5">Why Choose Arafat Paints?</h4>
    <p>When you choose Arafat Paints, you’re choosing a brand you can trust for quality, reliability, and expertise. Here’s why:</p>
    <ul>
        <li>High-performance products for both residential and commercial applications.</li>
        <li>A wide range of color options and finishes to suit every style.</li>
        <li>Eco-friendly and non-toxic paint solutions for a healthier environment.</li>
        <li>Personalized service with a focus on meeting the specific needs of each client.</li>
        <li>Expert technical support to guide you through your painting projects.</li>
    </ul>

    <p>We are proud to be a part of many successful projects over the years and look forward to continuing our tradition of excellence. Thank you for choosing Arafat Paints & Varnish Ltd – where quality meets color!</p>
</main>

@section Styles {
    <style>
        .jumbotron {
            background-color: #007bff;
            border-radius: 0;
        }

        h2 {
            color: #007bff;
        }

        ul {
            list-style-type: none;
            padding-left: 0;
        }

            ul li {
                padding: 5px 0;
            }
    </style>
}

EmployeeManagement/Views/Home/Contact.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Contact";
    ViewBag.Message = "Get in touch with us!";
}

<main class="container py-5" aria-labelledby="contactTitle">
    <h2 id="contactTitle" class="mb-3">@ViewBag.Title</h2>
    <h5 class="text-muted mb-4">@ViewBag.Message</h5>

    <address>
        <strong>Arafat Paints & Varnish Ltd</strong><br />
        Kali Bari Rd, Barishal 8200<br />
        <abbr title="Phone">P:</abbr> 01904-306730
    </address>

    <h4 class="mt-4">Hours</h4>
    <ul>
        <li><strong>Closed</strong></li>
        <li><strong>Opens:</strong> 9:00 AM</li>
    </ul>

    <h4 class="mt-4">Support & Sales</h4>
    <address>
        <strong>Email:</strong> <a href="mailto:info@arafatpaints.com">info@arafatpaints.com</a><br />
        <strong>Phone:</strong> 01904-306730
    </address>
</main>

@section Styles {
    <style>
        .container {
            max-width: 800px;
            margin: auto;
            background-color: #FFFFFF,;
            border-radius: 8px;
            padding: 2rem;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
        }

        h2 {
            color: #2d3e50;
        }

        h5, address {
            color: #6c757d;
        }

        h4 {
            color: #007bff;
            margin-top: 1.5rem;
        }

        ul {
            list-style: none;
            padding-left: 0;
        }

            ul li {
                margin-bottom: 0.5rem;
            }

        a {
            color: #007bff;
            text-decoration: none;
        }

            a:hover {
                text-decoration: underline;
            }
    </style>
}

EmployeeManagement/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Dashboard - Arafat Paints EMS";
}

<h1 class="text-center my-4">Arafat Paints Employee Management</h1>

<div class="container">

    <!-- Intro Section -->
    <div class="jumbotron bg-primary text-white text-center">
        <h2>Welcome to the EMS Dashboard</h2>
        <p>Manage your workforce, shifts, attendance, payroll and more—all in one place.</p>
    </div>

    <!-- Navigation Cards -->
    <div class="row">
        <!-- Employee -->
        <div class="col-sm-6 col-md-4 mb-4">
            <div class="card h-100 shadow-sm">
                <div class="card-body text-center">
                    <h5 class="card-title">Employees</h5>
                    <p class="card-text">Add, view and update employee records.</p>
                    <a href="@Url.Action("Index", "Employees")" class="btn btn-primary">View Employees</a>
                    <a href="@Url.Action("Create", "Employees")" class="btn btn-outline-primary mt-2">Add Employee</a>
                </div>
            </div>
        </div>

        <!-- Shifts -->
        <div class="col-sm-6 col-md-4 mb-4">
            <div class="card h-100 shadow-sm">
                <div class="card-body text-center">
                    <h5 class="card-title">Shifts</h5>
                    <p class="card-text">Define and manage work shifts.</p>
                    <a href="@Url.Action("Index", "Shift")" class="btn btn-primary">View Shifts</a>
                    <a href="@Url.Action("Create", "Shift")" class="btn btn-outline-primary mt-2">Add Shift</a>
                </div>
            </div>
        </div>

        <!-- Attendance -->
        <div class="col-sm-6 col-md-4 mb-4">
            <div class="card h-100 shadow-sm">
                <div class="card-body text-center">
                    <h5 class="card-title">Attendance</h5>
                    <p class="card-text">Log and review attendance entries.</p>
                    <a href="@Url.Action("Index", "Attendance")" class="btn btn-primary">View Attendance</a>
                    <a href="@Url.Action("Create", "Attendances")" class="btn btn-outline-primary mt-2">Log Attendance</a>
                </div>
            </div>
        </div>

        <!-- Leaves -->
        <div class="col-sm-6 col-md-4 mb-4">
            <div class="card h-100 shadow-sm">
                <div class="card-body text-center">
                    <h5 class="card-title">Leave Requests</h5>
                    <p class="card-text">Approve or reject leaves.</p>
                    <a href="@Url.Action("Index", "Leave")" class="btn btn-primary">View Leaves</a>
                    <a href="@Url.Action("Create", "Leave")" class="btn btn-outline-primary mt-2">Add Leave</a>
                </div>
            </div>
        </div>

        <!-- Payroll -->
        <div class="col-sm-6 col-md-4 mb-4">
            <div class="card h-100 shadow-sm">
                <div class="card-body text-center">
                    <h5 class="card-title">Payroll</h5>
                    <p class="card-text">Generate and view payroll records.</p>
                    <a href="@Url.Action("Index", "Payroll")" class="btn btn-primary">View Payroll</a>
                    <a href="@Url.Action("Create", "Payroll")" class="btn btn-outline-primary mt-2">Add Payroll</a>
                </div>
            </div>
        </div>

        <!-- Productivity -->
        <div class="col-sm-6 col-md-4 mb-4">
            <div class="card h-100 shadow-sm">
                <div class="card-body text-center">
                    <h5 class="card-title">Productivity</h5>
                    <p class="card-text">Track daily task outputs.</p>
                    <a href="@Url.Action("Index", "Productivities")" class="btn btn-primary">View Reports</a>
                    <a href="@Url.Action("Create", "Productivities")" class="btn btn-outline-primary mt-2">Add Record</a>
                </div>
            </div>
        </div>
    </div>
</div>

@section Styles {
    <style>
        .jumbotron { background-color: #007bff; }
        .card-title { font-size: 1.25rem; }
        .card-text { font-size: 0.9rem; color: #555; }
        .btn-outline-primary { border-color: #007bff; color: #007bff; }
        .btn-outline-primary:hover { background-color: #007bff; color: white; }
    </style>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}